### PR TITLE
Updated to Julia 1.0.3

### PR DESCRIPTION
**Pull request by ChandlerKilpatrick1**
Please see the issue I tagged you in, but after that, this should be ready to merge in.

### CODE REVIEW

**Comment by zsunberg** [comment]
@ChandlerKilpatrick1 Thanks for doing this! Can you switch from using the REQUIRE file to a Project.toml and update the .travis.yml file to look like this: https://github.com/JuliaPOMDP/POMCPOW.jl/blob/master/.travis.yml (except with POMCPOW replaced with VDPTag2, etc)?

**Comment by ChandlerKilpatrick1** [comment]
I've already switched to a Project/Manifest file setup and removed the Require file.

**Comment by zsunberg** [comment]
Oh oops - I was looking at the wrong thing

**Comment by ChandlerKilpatrick1** [comment]
We could remove the type cast from `h` here: `@recipe function f(pomdp::VDPTagPOMDP, h::POMDPHistory{TagState})` but other than that, I am not sure how to fix this build error.

**Comment by zsunberg** [comment]
Thanks @ChandlerKilpatrick1! I'm going to merge this now

**Pull request merged**
